version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: k8t
    main: ./cmd/k8t
    binary: k8t
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: k8t
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: yourorg
    name: k8t
  draft: false
  prerelease: auto
  mode: append

brews:
  - name: k8t
    repository:
      owner: yourorg
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/yourorg/k8t
    description: Kubernetes administration toolkit for diagnosing common issues
    license: Apache-2.0
    dependencies:
      - name: kubernetes-cli
        type: optional
    install: |
      bin.install "k8t"
    test: |
      system "#{bin}/k8t", "version"
